export const columns = [
  {
    name: "imie",
    label: "IMIE",
    options: {
      filter: true,
      sort: true,
    },
  },
  {
    name: "nom",
    label: "nom",
    options: {
      filter: true,
      sort: true,
    },
  },
  {
    name: "référence",
    label: "référence",
    options: {
      filter: true,
      sort: true,
    },
  },
  {
    name: "marque",
    label: "Marque",
    options: {
      filter: true,
      sort: true,
    },
  },
  {
    name: "Région",
    label: "Région",
    options: {
      filter: true,
      sort: true,
    },
  },
  {
    name: "Province",
    label: "Province",
    options: {
      filter: true,
      sort: true,
    },
  },
  {
    name: "VaccinType",
    label: "Vaccin type",
    options: {
      filter: true,
      sort: true,
    },
  },
  {
    name: "Etat",
    label: "Etat",
    options: {
      filter: false,
      sort: false,
    },
  },
  {
    name: "Type",
    label: "Type",
    options: {
      filter: true,
      sort: true,
    },
  },
  {
    name: "localisation",
    label: "localisation",
    options: {
      filter: true,
      sort: true,
    },
  },
];

export const rows = [
  {
    imie: "123456789012345",
    nom: "ULC PHARMACEUTIQUE AMZMIZ",
    référence: "REF001",
    marque: "Marque A",
    Région: "Île-de-France",
    Province: "Paris",
    VaccinType: "Vaccin X",
    Etat: "Disponible",
    Type: "Type A",
    localisation: "Centre A",
  },
  {
    imie: "987654321098765",
    nom: "ULC PHARMACEUTIQUE SIDI LAAROUSSI",
    référence: "REF002",
    marque: "Marque B",
    Région: "Auvergne-Rhône-Alpes",
    Province: "Lyon",
    VaccinType: "Vaccin Y",
    Etat: "Épuisé",
    Type: "Type B",
    localisation: "Centre B",
  },
  {
    imie: "456789123456789",
    nom: "ULC PHARMACEUTIQUE LABRIKIYINE",
    référence: "REF003",
    marque: "Marque C",
    Région: "Provence-Alpes-Côte d'Azur",
    Province: "Marseille",
    VaccinType: "Vaccin Z",
    Etat: "Disponible",
    Type: "Type C",
    localisation: "Centre C",
  },
  {
    imie: "789012345678901",
    nom: "ULC PHARMACEUTIQUE EZZAOUIT",
    référence: "REF004",
    marque: "Marque D",
    Région: "Nouvelle-Aquitaine",
    Province: "Bordeaux",
    VaccinType: "Vaccin A",
    Etat: "Disponible",
    Type: "Type A",
    localisation: "Centre D",
  },
  {
    imie: "321654987012345",
    nom: "ULC PHARMACEUTIQUE ALMIS GUIGOU",
    référence: "REF005",
    marque: "Marque E",
    Région: "Occitanie",
    Province: "Toulouse",
    VaccinType: "Vaccin B",
    Etat: "En attente",
    Type: "Type B",
    localisation: "Centre E",
  },
  {
    imie: "654321789012345",
    nom: "ULC PHARMACEUTIQUE EZZAOUIT",
    référence: "REF006",
    marque: "Marque F",
    Région: "Hauts-de-France",
    Province: "Lille",
    VaccinType: "Vaccin C",
    Etat: "Épuisé",
    Type: "Type C",
    localisation: "Centre F",
  },
  {
    imie: "135792468012345",
    nom: "ULC PHARMACEUTIQUE RAS EL OUAD",
    référence: "REF007",
    marque: "Marque G",
    Région: "Grand Est",
    Province: "Strasbourg",
    VaccinType: "Vaccin D",
    Etat: "Disponible",
    Type: "Type D",
    localisation: "Centre G",
  },
  {
    imie: "246813579012345",
    nom: "ULC PHARMACEUTIQUE BNI OUAL",
    référence: "REF008",
    marque: "Marque H",
    Région: "Bretagne",
    Province: "Rennes",
    VaccinType: "Vaccin E",
    Etat: "En attente",
    Type: "Type E",
    localisation: "Centre H",
  },
  {
    imie: "987123456012345",
    nom: "ULC PHARMACEUTIQUE ALMIS GUIGOU",
    référence: "REF009",
    marque: "Marque I",
    Région: "Normandie",
    Province: "Caen",
    VaccinType: "Vaccin F",
    Etat: "Disponible",
    Type: "Type F",
    localisation: "Centre I",
  },
  {
    imie: "456789321012345",
    nom: "ULC PHARMACEUTIQUE MERIJA",
    référence: "REF010",
    marque: "Marque J",
    Région: "Centre-Val de Loire",
    Province: "Orléans",
    VaccinType: "Vaccin G",
    Etat: "Épuisé",
    Type: "Type G",
    localisation: "Centre J",
  },
];
