export const rows = [
  {
    id: 1,
    photo: "https://picsum.photos/50?random=1",
    name: "Ali Ben Ahmed",
    poste: "Technicien",
    hireDate: "2021-03-15",
    cin: "A123456",
    region: "Casablanca-Settat",
    province: "Casablanca",
    age: 35,
    sex: "M",
    phone: "+212 6 12 34 56 78",
    email: "ali.benahmed@example.com",
    address: "12 Rue de Fès, 20000 Casablanca, Maroc",
  },
  {
    id: 2,
    photo: "https://picsum.photos/50?random=2",
    name: "Hassan El Yacoubi",
    poste: "Infirmier",
    hireDate: "2020-07-01",
    cin: "B234567",
    region: "Rabat-Salé-Kénitra",
    province: "Rabat",
    age: 29,
    sex: "M",
    phone: "+212 6 23 45 67 89",
    email: "hassan.elyacoubi@example.com",
    address: "5 Avenue Mohammed V, 10000 Rabat, Maroc",
  },
  {
    id: 3,
    photo: "https://picsum.photos/50?random=3",
    name: "Fatima Zahra Idrissi",
    poste: "Docteur",
    hireDate: "2019-11-20",
    cin: "C345678",
    region: "Marrakech-Safi",
    province: "Marrakech",
    age: 42,
    sex: "F",
    phone: "+212 5 12 34 56 78",
    email: "fatima.idrissi@example.com",
    address: "24 Boulevard Zerktouni, 40000 Marrakech, Maroc",
  },
  {
    id: 4,
    photo: "https://picsum.photos/50?random=4",
    name: "Said Bakkali",
    poste: "Technicien",
    hireDate: "2022-01-10",
    cin: "D456789",
    region: "Tanger-Tétouan-Al Hoceïma",
    province: "Tanger",
    age: 31,
    sex: "M",
    phone: "+212 5 23 45 67 89",
    email: "said.bakkali@example.com",
    address: "8 Rue de la Liberté, 90000 Tanger, Maroc",
  },
  {
    id: 5,
    photo: "https://picsum.photos/50?random=5",
    name: "Nour El Houda Amrani",
    poste: "Infirmier",
    hireDate: "2023-05-22",
    cin: "E567890",
    region: "Fès-Meknès",
    province: "Fès",
    age: 27,
    sex: "F",
    phone: "+212 6 55 66 77 88",
    email: "nour.amrani@example.com",
    address: "15 Rue Al Atlas, 30000 Fès, Maroc",
  },
  {
    id: 6,
    photo: "https://picsum.photos/50?random=6",
    name: "Mohamed Amine El Hariri",
    poste: "Docteur",
    hireDate: "2018-09-30",
    cin: "F678901",
    region: "Souss-Massa",
    province: "Agadir",
    age: 39,
    sex: "M",
    phone: "+212 5 66 77 88 99",
    email: "mohamed.elhariri@example.com",
    address: "10 Place Moulay El Hassan, 46000 Agadir, Maroc",
  },
];
