export const rows = [
  {
    id: 1,
    Etat: "actif",
    Nom: "UMMC OUMEJRANE TINGHIR",
    Région: "Drâa-Tafilalet",
    Province: "Tinghir",
    Coordinateur: "Oumaima LALLALEN",
    Chargé_de_suivie: "ANNOUN Anass",
    Technicien: "omar omar",
    Docteur: "DR CHAACHOUE",
    Mail: "UMMC_OUMEJRANE@mediot.io",
    Num: "06-61-00-11-22",
    Position: "33.832992, -5.159987",
  },
  {
    id: 2,
    Etat: "actif",
    Nom: "UMMC OUARZAZATE CENTRE",
    Région: "badr",
    Province: "Ouarzazate",
    Coordinateur: "ELHAJ Othmane",
    Chargé_de_suivie: "BOUZEKRI Fatima",
    Technicien: "el bakkali ahmed",
    Docteur: "DR MOUJEB",
    Mail: "UMMC_OUARZAZATE@mediot.io",
    Num: "06-62-12-13-14",
    Position: "30.933543, -6.907874",
  },
  {
    id: 3,
    Etat: "inactif",
    Nom: "UMMC RISSANI",
    Région: "Drâa-Tafilalet",
    Province: "Errachidia",
    Coordinateur: "AMRAOUI Soumaya",
    Chargé_de_suivie: "ESSOUBAIK Mourad",
    Technicien: "khalid bouchra",
    Docteur: "DR ELKETTANI",
    Mail: "UMMC_RISSANI@mediot.io",
    Num: "06-63-14-15-16",
    Position: "31.285743, -4.274330",
  },
  {
    id: 4,
    Etat: "actif",
    Nom: "UMMC MARRAKECH MEDINA",
    Région: "Marrakech-Safi",
    Province: "Marrakech",
    Coordinateur: "BENKHADRA Hamza",
    Chargé_de_suivie: "ZIYANI Naima",
    Technicien: "mohamed said",
    Docteur: "DR ABOUCHAIB",
    Mail: "UMMC_MARRAKECH@mediot.io",
    Num: "06-64-17-18-19",
    Position: "31.630520, -7.989413",
  },
  {
    id: 5,
    Etat: "inactif",
    Nom: "UMMC CASABLANCA AIN SEBAA",
    Région: "Casablanca-Settat",
    Province: "Casablanca",
    Coordinateur: "BOUHRIRI Khalid",
    Chargé_de_suivie: "LARBI Mohamed",
    Technicien: "el khattab yassir",
    Docteur: "DR OUCHNOU",
    Mail: "UMMC_CASABLANCA@mediot.io",
    Num: "06-65-20-21-22",
    Position: "33.592789, -7.613197",
  },
  {
    id: 6,
    Etat: "actif",
    Nom: "UMMC FES SAISS",
    Région: "Fès-Meknès",
    Province: "Fès",
    Coordinateur: "BELKASSEM Amine",
    Chargé_de_suivie: "ELHANI Amina",
    Technicien: "lahcen chafik",
    Docteur: "DR BELFADEL",
    Mail: "UMMC_FES@mediot.io",
    Num: "06-66-23-24-25",
    Position: "33.999917, -4.997717",
  },
  {
    id: 7,
    Etat: "inactif",
    Nom: "UMMC RABAT AGDAL",
    Région: "Rabat-Salé-Kénitra",
    Province: "Rabat",
    Coordinateur: "MAHFOUDI Laila",
    Chargé_de_suivie: "BOULHANE Youssef",
    Technicien: "hassan darif",
    Docteur: "DR MAHJOUB",
    Mail: "UMMC_RABAT@mediot.io",
    Num: "06-67-26-27-28",
    Position: "34.015132, -6.834512",
  },
  {
    id: 8,
    Etat: "actif",
    Nom: "UMMC TANGER VILLE",
    Région: "Tanger-Tétouan-Al Hoceïma",
    Province: "Tanger",
    Coordinateur: "DERKAOUI Rachid",
    Chargé_de_suivie: "KADI Karima",
    Technicien: "faissal bouchaib",
    Docteur: "DR KARIMI",
    Mail: "UMMC_TANGER@mediot.io",
    Num: "06-68-29-30-31",
    Position: "35.759465, -5.834475",
  },
  {
    id: 9,
    Etat: "inactif",
    Nom: "UMMC AGADIR SOUSS MASSA",
    Région: "Souss-Massa",
    Province: "Agadir",
    Coordinateur: "AFOUF Aziz",
    Chargé_de_suivie: "ESSAADI Yassir",
    Technicien: "mehdi el hassani",
    Docteur: "DR ZERHOUNI",
    Mail: "UMMC_AGADIR@mediot.io",
    Num: "06-69-32-33-34",
    Position: "30.427755, -9.598107",
  },
  {
    id: 10,
    Etat: "actif",
    Nom: "UMMC LAAYOUNE BOUJDOUR",
    Région: "Laâyoune-Sakia El Hamra",
    Province: "Laâyoune",
    Coordinateur: "OUHMADA Meryem",
    Chargé_de_suivie: "ZAKI Mehdi",
    Technicien: "mohamed hamza",
    Docteur: "DR IDRISSI",
    Mail: "UMMC_LAAYOUNE@mediot.io",
    Num: "06-60-35-36-37",
    Position: "27.148145, -13.199186",
  },
  {
    id: 11,
    Etat: "actif",
    Nom: "UMMC AGADIR SOUSS MASSA",
    Région: "Souss-Massa",
    Province: "Agadir",
    Coordinateur: "EL YAZAMI Sara",
    Chargé_de_suivie: "EL AMRANI Ahmed",
    Technicien: "YASSINE Abdellah",
    Docteur: "DR TAHIRI",
    Mail: "UMMC_AGADIR@mediot.io",
    Num: "06-61-12-13-14",
    Position: "30.427755, -9.598107",
  },
  {
    id: 12,
    Etat: "actif",
    Nom: "UMMC RABAT SALE ZEMMOUR",
    Région: "Rabat-Salé-Kénitra",
    Province: "Rabat",
    Coordinateur: "BENSLIMANE Rachid",
    Chargé_de_suivie: "BERRADA Hassan",
    Technicien: "EL MOKHTAR Hicham",
    Docteur: "DR CHERKAOUI",
    Mail: "UMMC_RABAT@mediot.io",
    Num: "06-62-25-26-27",
    Position: "34.020882, -6.841650",
  },
  {
    id: 13,
    Etat: "actif",
    Nom: "UMMC CASABLANCA ANFA",
    Région: "Casablanca-Settat",
    Province: "Casablanca",
    Coordinateur: "RAJI Fatima",
    Chargé_de_suivie: "TAHIRI Youssef",
    Technicien: "KADI Mourad",
    Docteur: "DR EL AZZOUZI",
    Mail: "UMMC_CASABLANCA@mediot.io",
    Num: "06-63-45-46-47",
    Position: "33.573110, -7.589843",
  },
  {
    id: 14,
    Etat: "actif",
    Nom: "UMMC TANGER TETOUAN",
    Région: "Tanger-Tétouan-Al Hoceïma",
    Province: "Tanger",
    Coordinateur: "LOUAHDI Samira",
    Chargé_de_suivie: "LAGHZAOUI Karim",
    Technicien: "GHALMI Rachid",
    Docteur: "DR NAJIM",
    Mail: "UMMC_TANGER@mediot.io",
    Num: "06-64-65-66-67",
    Position: "35.759465, -5.834037",
  },
  {
    id: 15,
    Etat: "actif",
    Nom: "UMMC OUJDA BERKANE",
    Région: "Oriental",
    Province: "Oujda",
    Coordinateur: "BENKHAYAL Naima",
    Chargé_de_suivie: "SLIMANI Abdel",
    Technicien: "NADIR Younes",
    Docteur: "DR LAMRINI",
    Mail: "UMMC_OUJDA@mediot.io",
    Num: "06-65-75-76-77",
    Position: "34.681391, -1.907591",
  },
  {
    id: 16,
    Etat: "actif",
    Nom: "UMMC FES MEKNES",
    Région: "Fès-Meknès",
    Province: "Fès",
    Coordinateur: "CHAFIK Hind",
    Chargé_de_suivie: "KHALDOUN Soufiane",
    Technicien: "BAZZI Youssef",
    Docteur: "DR AMRAOUI",
    Mail: "UMMC_FES@mediot.io",
    Num: "06-66-85-86-87",
    Position: "34.033333, -5.000000",
  },
  {
    id: 17,
    Etat: "actif",
    Nom: "UMMC BENI MELLAL KHENIFRA",
    Région: "Béni Mellal-Khénifra",
    Province: "Beni Mellal",
    Coordinateur: "ZOUITNI Imane",
    Chargé_de_suivie: "EL HAYANI Abdellah",
    Technicien: "OUKACHA Ahmed",
    Docteur: "DR EL BAKKALI",
    Mail: "UMMC_BENI@mediot.io",
    Num: "06-67-95-96-97",
    Position: "32.339439, -6.349382",
  },
  {
    id: 18,
    Etat: "actif",
    Nom: "UMMC MARRAKECH SAFI",
    Région: "Marrakech-Safi",
    Province: "Marrakech",
    Coordinateur: "BENTALEB Hajar",
    Chargé_de_suivie: "HAMMOUDA Laila",
    Technicien: "CHERIF Rachid",
    Docteur: "DR OUARDI",
    Mail: "UMMC_MARRAKECH@mediot.io",
    Num: "06-68-15-16-17",
    Position: "31.629472, -7.981084",
  },
  {
    id: 19,
    Etat: "actif",
    Nom: "UMMC TETOUAN HOCEIMA",
    Région: "Tanger-Tétouan-Al Hoceïma",
    Province: "Tétouan",
    Coordinateur: "DRAISSI Yasmina",
    Chargé_de_suivie: "ALAMI Soukaina",
    Technicien: "MAHFOUDI Abdelkader",
    Docteur: "DR JAAFARI",
    Mail: "UMMC_TETOUAN@mediot.io",
    Num: "06-69-25-26-27",
    Position: "35.578483, -5.368370",
  },
  {
    id: 20,
    Etat: "actif",
    Nom: "UMMC EL JADIDA",
    Région: "Casablanca-Settat",
    Province: "El Jadida",
    Coordinateur: "KHARCHI Khalid",
    Chargé_de_suivie: "MOUKHLISS Salma",
    Technicien: "ZIANI Abdelilah",
    Docteur: "DR FIKRI",
    Mail: "UMMC_ELJADIDA@mediot.io",
    Num: "06-70-35-36-37",
    Position: "33.256047, -8.507209",
  },
  {
    id: 21,
    Etat: "actif",
    Nom: "ULC TANGER LOGISTIQUE",
    Région: "Tanger-Tétouan-Al Hoceïma",
    Province: "Tanger",
    Coordinateur: "AZIZI Rachid",
    Chargé_de_suivie: "LAMRHARI Karim",
    Technicien: "SALHI Mohamed",
    Responsable_Stock: "DRISSI Saad",
    Mail: "ULC_TANGER@logistic.io",
    Num: "06-71-45-46-47",
    Position: "35.759465, -5.834037",
  },
  {
    id: 22,
    Etat: "actif",
    Nom: "ULC CASABLANCA NOUACEUR",
    Région: "Casablanca-Settat",
    Province: "Nouaceur",
    Coordinateur: "EL BOUKILI Hicham",
    Chargé_de_suivie: "SAADI Fatima",
    Technicien: "KHALDOUN Youssef",
    Responsable_Stock: "OUARDI Mourad",
    Mail: "ULC_CASABLANCA@logistic.io",
    Num: "06-72-85-86-87",
    Position: "33.369970, -7.589843",
  },
  {
    id: 23,
    Etat: "actif",
    Nom: "ULC AGADIR LOGISTIQUE",
    Région: "Souss-Massa",
    Province: "Agadir",
    Coordinateur: "KARIMI Sara",
    Chargé_de_suivie: "LAAROUSSI Mehdi",
    Technicien: "BENALI Khaled",
    Responsable_Stock: "NAJIM Karim",
    Mail: "ULC_AGADIR@logistic.io",
    Num: "06-73-95-96-97",
    Position: "30.427755, -9.598107",
  },
  {
    id: 24,
    Etat: "actif",
    Nom: "ULC MARRAKECH LOGISTIQUE",
    Région: "Marrakech-Safi",
    Province: "Marrakech",
    Coordinateur: "TALBI Amina",
    Chargé_de_suivie: "EL OMRANI Imane",
    Technicien: "BOUTALEB Younes",
    Responsable_Stock: "SALHI Rachid",
    Mail: "ULC_MARRAKECH@logistic.io",
    Num: "06-74-05-06-07",
    Position: "31.629472, -7.981084",
  },
  {
    id: 25,
    Etat: "actif",
    Nom: "ULC FES LOGISTIQUE",
    Région: "Fès-Meknès",
    Province: "Fès",
    Coordinateur: "EL FASSI Fatima",
    Chargé_de_suivie: "NASSIRI Samir",
    Technicien: "EL KHAYATI Abdellah",
    Responsable_Stock: "LAMRINI Hassan",
    Mail: "ULC_FES@logistic.io",
    Num: "06-75-15-16-17",
    Position: "34.033333, -5.000000",
  },
  {
    id: 26,
    Etat: "actif",
    Nom: "ULC OUJDA LOGISTIQUE",
    Région: "Oriental",
    Province: "Oujda",
    Coordinateur: "FARISSI Imane",
    Chargé_de_suivie: "HAJJI Omar",
    Technicien: "NAJMI Yassine",
    Responsable_Stock: "BENDAHI Khaled",
    Mail: "ULC_OUJDA@logistic.io",
    Num: "06-76-25-26-27",
    Position: "34.681391, -1.907591",
  },
  {
    id: 27,
    Etat: "actif",
    Nom: "ULC BENI MELLAL LOGISTIQUE",
    Région: "Béni Mellal-Khénifra",
    Province: "Beni Mellal",
    Coordinateur: "ZAKI Soukaina",
    Chargé_de_suivie: "BENSLIMANE Youssef",
    Technicien: "EL MAHROUG Rachid",
    Responsable_Stock: "KETTANI Hassan",
    Mail: "ULC_BENI@logistic.io",
    Num: "06-77-35-36-37",
    Position: "32.339439, -6.349382",
  },
  {
    id: 28,
    Etat: "actif",
    Nom: "ULC LAAYOUNE LOGISTIQUE",
    Région: "Laâyoune-Sakia El Hamra",
    Province: "Laâyoune",
    Coordinateur: "FARHAT Karima",
    Chargé_de_suivie: "NAJI Mehdi",
    Technicien: "CHAKIR Hamid",
    Responsable_Stock: "TAIBI Rachid",
    Mail: "ULC_LAAYOUNE@logistic.io",
    Num: "06-78-45-46-47",
    Position: "27.148145, -13.199186",
  },
  {
    id: 29,
    Etat: "actif",
    Nom: "ULC MEKNES LOGISTIQUE",
    Région: "Fès-Meknès",
    Province: "Meknès",
    Coordinateur: "BENJELLOUN Imane",
    Chargé_de_suivie: "OUBELKAS Omar",
    Technicien: "SABRI Youssef",
    Responsable_Stock: "EL GHALMI Mourad",
    Mail: "ULC_MEKNES@logistic.io",
    Num: "06-79-55-56-57",
    Position: "33.889084, -5.547008",
  },
  {
    id: 30,
    Etat: "actif",
    Nom: "ULC EL JADIDA LOGISTIQUE",
    Région: "Casablanca-Settat",
    Province: "El Jadida",
    Coordinateur: "BAHRAOUI Rachid",
    Chargé_de_suivie: "AKROUM Soukaina",
    Technicien: "AMZIL Khaled",
    Responsable_Stock: "CHAFIK Samir",
    Mail: "ULC_ELJADIDA@logistic.io",
    Num: "06-70-35-36-37",
    Position: "33.256047, -8.507209",
  },
];
