export const rows = [
  {
    "id": 1,
    "Etat": "actif",
    "Nom": "UMMC OUMEJRANE TINGHIR",
    "Région": "Drâa-Tafilalet",
    "Province": "Tinghir",
    "Coordinateur": "LALLALEN Oumaima",
    "Chargé_de_suivie": "ANNOUN Anass",
    "Technicien": "omar omar",
    "Docteur": "DR CHAACHOUE",
    "Mail": "UMMC_OUMEJRANE@mediot.io",
    "Num": "06-61-00-11-22",
    "Position": "33.832992, -5.159987"
  },
  {
    "id": 2,
    "Etat": "actif",
    "Nom": "UMMC OUARZAZATE CENTRE",
    "Région": "Drâa-Tafilalet",
    "Province": "Ouarzazate",
    "Coordinateur": "ELHAJ Othmane",
    "Chargé_de_suivie": "BOUZEKRI Fatima",
    "Technicien": "el bakkali ahmed",
    "Docteur": "DR MOUJEB",
    "Mail": "UMMC_OUARZAZATE@mediot.io",
    "Num": "06-62-12-13-14",
    "Position": "30.933543, -6.907874"
  },
  {
    "id": 3,
    "Etat": "inactif",
    "Nom": "UMMC RISSANI",
    "Région": "Drâa-Tafilalet",
    "Province": "Errachidia",
    "Coordinateur": "AMRAOUI Soumaya",
    "Chargé_de_suivie": "ESSOUBAIK Mourad",
    "Technicien": "khalid bouchra",
    "Docteur": "DR ELKETTANI",
    "Mail": "UMMC_RISSANI@mediot.io",
    "Num": "06-63-14-15-16",
    "Position": "31.285743, -4.274330"
  },
  {
    "id": 4,
    "Etat": "actif",
    "Nom": "UMMC MARRAKECH MEDINA",
    "Région": "Marrakech-Safi",
    "Province": "Marrakech",
    "Coordinateur": "BENKHADRA Hamza",
    "Chargé_de_suivie": "ZIYANI Naima",
    "Technicien": "mohamed said",
    "Docteur": "DR ABOUCHAIB",
    "Mail": "UMMC_MARRAKECH@mediot.io",
    "Num": "06-64-17-18-19",
    "Position": "31.630520, -7.989413"
  },
  {
    "id": 5,
    "Etat": "inactif",
    "Nom": "UMMC CASABLANCA AIN SEBAA",
    "Région": "Casablanca-Settat",
    "Province": "Casablanca",
    "Coordinateur": "BOUHRIRI Khalid",
    "Chargé_de_suivie": "LARBI Mohamed",
    "Technicien": "el khattab yassir",
    "Docteur": "DR OUCHNOU",
    "Mail": "UMMC_CASABLANCA@mediot.io",
    "Num": "06-65-20-21-22",
    "Position": "33.592789, -7.613197"
  },
  {
    "id": 6,
    "Etat": "actif",
    "Nom": "UMMC FES SAISS",
    "Région": "Fès-Meknès",
    "Province": "Fès",
    "Coordinateur": "BELKASSEM Amine",
    "Chargé_de_suivie": "ELHANI Amina",
    "Technicien": "lahcen chafik",
    "Docteur": "DR BELFADEL",
    "Mail": "UMMC_FES@mediot.io",
    "Num": "06-66-23-24-25",
    "Position": "33.999917, -4.997717"
  },
  {
    "id": 7,
    "Etat": "inactif",
    "Nom": "UMMC RABAT AGDAL",
    "Région": "Rabat-Salé-Kénitra",
    "Province": "Rabat",
    "Coordinateur": "MAHFOUDI Laila",
    "Chargé_de_suivie": "BOULHANE Youssef",
    "Technicien": "hassan darif",
    "Docteur": "DR MAHJOUB",
    "Mail": "UMMC_RABAT@mediot.io",
    "Num": "06-67-26-27-28",
    "Position": "34.015132, -6.834512"
  },
  {
    "id": 8,
    "Etat": "actif",
    "Nom": "UMMC TANGER VILLE",
    "Région": "Tanger-Tétouan-Al Hoceïma",
    "Province": "Tanger",
    "Coordinateur": "DERKAOUI Rachid",
    "Chargé_de_suivie": "KADI Karima",
    "Technicien": "faissal bouchaib",
    "Docteur": "DR KARIMI",
    "Mail": "UMMC_TANGER@mediot.io",
    "Num": "06-68-29-30-31",
    "Position": "35.759465, -5.834475"
  },
  {
    "id": 9,
    "Etat": "inactif",
    "Nom": "UMMC AGADIR SOUSS MASSA",
    "Région": "Souss-Massa",
    "Province": "Agadir",
    "Coordinateur": "AFOUF Aziz",
    "Chargé_de_suivie": "ESSAADI Yassir",
    "Technicien": "mehdi el hassani",
    "Docteur": "DR ZERHOUNI",
    "Mail": "UMMC_AGADIR@mediot.io",
    "Num": "06-69-32-33-34",
    "Position": "30.427755, -9.598107"
  },
  {
    "id": 10,
    "Etat": "actif",
    "Nom": "UMMC LAAYOUNE BOUJDOUR",
    "Région": "Laâyoune-Sakia El Hamra",
    "Province": "Laâyoune",
    "Coordinateur": "OUHMADA Meryem",
    "Chargé_de_suivie": "ZAKI Mehdi",
    "Technicien": "mohamed hamza",
    "Docteur": "DR IDRISSI",
    "Mail": "UMMC_LAAYOUNE@mediot.io",
    "Num": "06-60-35-36-37",
    "Position": "27.148145, -13.199186"
  },
  {
    "id": 11,
    "Nom": "badr",
    "Docteur": "fakhir"
  }
];