export const rows = [
  {
    ID: 1,
    "Nom de la Pièce": "Moteur",
    Catégorie: "Mécanique",
    Quantite: 6,
    "Date d'Entrée": "2024-01-15",
    Emplacement: "Entrepôt A",
    "État de la Pièce": "Disponible",
    Reference: "REF-001",
    Responsable: "Jean Dupont",
    Compatibilité: "Modèle X",
    Observations: "Aucun",
  },
  {
    ID: 2,
    "Nom de la Pièce": "Capteur de Température",
    Catégorie: "Électronique",
    Quantite: 10,
    "Date d'Entrée": "2024-02-20",
    Emplacement: "Entrepôt B",
    "État de la Pièce": "En attente",
    Reference: 2,
    Responsable: "Marie Curie",
    Compatibilité: "Modèle Y",
    Observations: "En cours de vérification",
  },
  {
    ID: 3,
    "Nom de la Pièce": "Batterie",
    Catégorie: "Énergétique",
    Quantite: 15,
    "Date d'Entrée": "2024-03-05",
    Emplacement: "Entrepôt C",
    "État de la Pièce": "Disponible",
    Reference: "REF-003",
    Responsable: "Pierre Martin",
    Compatibilité: "Modèle Z",
    Observations: "Bon état",
  },
  {
    ID: 4,
    "Nom de la Pièce": "Filtre",
    Catégorie: "Mécanique",
    Quantite: 20,
    "Date d'Entrée": "2024-04-10",
    Emplacement: "Entrepôt A",
    "État de la Pièce": "Rupture de stock",
    Reference: "REF-004",
    Responsable: "Lucie Bernard",
    Compatibilité: "Modèle W",
    Observations: "À commander",
  },
  {
    ID: 5,
    "Nom de la Pièce": "Écran",
    Catégorie: "Électronique",
    Quantite: 8,
    "Date d'Entrée": "2024-05-12",
    Emplacement: "Entrepôt B",
    "État de la Pièce": "Disponible",
    Reference: "REF-005",
    Responsable: "Alice Lefèvre",
    Compatibilité: "Modèle X",
    Observations: "À vérifier avant utilisation",
  },
];
