

export const rows = [
  {
    id: 1,
    Site: "UMMCr OUMEJRANE TINGHIR",
    date: "2024-08-22",
    technicien: "Oumaima LALLALEN",
    typeIntervention: "Réparation",
    statut: "Terminé",
    lieu: "Casablanca",
    description: "Réparation du système de climatisation dans le bâtiment A.",
    heureDebut: "08:00",
    heureFin: "10:00",
    commentaires: "Intervention réussie, le système fonctionne normalement.",
  },
  {
    id: 2,
    Site: "UMMC  TINGHIR",
    date: "2024-08-23",
    technicien: "Mohamed RAZIN",
    typeIntervention: "Maintenance Préventive",
    statut: "Terminé",
    lieu: "Rabat",
    description: "Maintenance préventive du générateur électrique.",
    heureDebut: "09:30",
    heureFin: "23:32",
    commentaires: "Vérification des niveaux de carburant et des filtres.",
  },
  {
    id: 3,
    Site: "UMMC OUMEJRANE ",
    date: "2024-08-24",
    technicien: "Ismail BELGHITI",
    typeIntervention: "Dépannage",
    statut: "Annulé",
    lieu: "Marrakech",
    description: "Dépannage du système de plomberie dans le bureau 12.",
    heureDebut: "18:00",
    heureFin: "13:00",
    commentaires: "L'intervention a été annulée par le client.",
  },
  {
    id: 4,
    Site: "UMMC RABAT",
    date: "2024-08-25",
    technicien: "Abderahmen AKRAN",
    typeIntervention: "Installation",
    statut: "Terminé",
    lieu: "Fès",
    description: "Installation d'un nouveau système de sécurité.",
    heureDebut: "14:00",
    heureFin: "17:00",
    commentaires:
      "Installation terminée avec succès, tous les équipements sont fonctionnels.",
  },
  {
    id: 5,
    Site: "UMMC TANGER",
    date: "2024-08-26",
    technicien: "Oumaima LALLALEN",
    typeIntervention: "Inspection",
    statut: "Terminé",
    lieu: "Agadir",
    description: "Inspection des équipements de ventilation.",
    heureDebut: "11:00",
    heureFin: "13:34",
    commentaires:
      "L'inspection est en cours, aucune anomalie détectée jusqu'à présent.",
  },
  {
    id: 6,
    Site: "UMMC CASABLANCA",
    date: "2024-08-27",
    technicien: "Mohamed RAZIN",
    typeIntervention: "Réparation",
    statut: "Terminé",
    lieu: "Tanger",
    description: "Réparation du système de chauffage central.",
    heureDebut: "15:00",
    heureFin: "17:30",
    commentaires: "Réparation effectuée, test complet réalisé avec succès.",
  },
  {
    id: 7,
    Site: "UMMC MARRAKECH",
    date: "2024-08-27",
    technicien: "Mohamed RAZIN",
    typeIntervention: "Réparation",
    statut: "Terminé",
    lieu: "Tanger",
    description: "Réparation du système de chauffage central.",
    heureDebut: "15:00",
    heureFin: "17:30",
    commentaires: "Réparation effectuée, test complet réalisé avec succès.",
  },
  {
    id: 8,
    Site: "UMMC SIDI IFNI",
    date: "2024-08-27",
    technicien: "Mohamed RAZIN",
    typeIntervention: "Réparation",
    statut: "Terminé",
    lieu: "Tanger",
    description: "Réparation du système de chauffage central.",
    heureDebut: "15:00",
    heureFin: "17:30",
    commentaires: "Réparation effectuée, test complet réalisé avec succès.",
  },
];
