import { TextField } from "@mui/material";
import React from "react";

const VehicleForm = ({ formData, handleChange }) => {
  return (
    <div>
      <TextField
        autoFocus
        margin="dense"
        label="IMIE"
        name="imie"
        type="text"
        fullWidth
        value={formData.imie}
        onChange={handleChange}
      />
      <TextField
        margin="dense"
        label="Immatriculation"
        name="immatriculation"
        type="text"
        fullWidth
        value={formData.immatriculation}
        onChange={handleChange}
      />
      <TextField
        margin="dense"
        label="Marque"
        name="marque"
        type="text"
        fullWidth
        value={formData.marque}
        onChange={handleChange}
      />
      <TextField
        margin="dense"
        label="Modèle"
        name="modele"
        type="text"
        fullWidth
        value={formData.modele}
        onChange={handleChange}
      />
      <TextField
        margin="dense"
        label="Année"
        name="annee"
        type="number"
        fullWidth
        value={formData.annee}
        onChange={handleChange}
      />
      <TextField
        margin="dense"
        label="Statut"
        name="statut"
        type="text"
        fullWidth
        value={formData.statut}
        onChange={handleChange}
      />
      <TextField
        margin="dense"
        label="Localisation"
        name="localisation"
        type="text"
        fullWidth
        value={formData.localisation}
        onChange={handleChange}
      />
      <TextField
        margin="dense"
        label="Conducteur"
        name="conducteur"
        type="text"
        fullWidth
        value={formData.conducteur}
        onChange={handleChange}
      />
      <TextField
        margin="dense"
        label="Image URL"
        name="image"
        type="text"
        fullWidth
        value={formData.image}
        onChange={handleChange}
      />
    </div>
  );
};

export default VehicleForm;
